---
title: "GoodTreeads"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load Libraries
library(rvest)
library(tidytext)
library(dplyr)
library(stringr)
library(collapsibleTree)
library(purrr)
```

[The Way of Kings](https://www.goodreads.com/book/show/7235533-the-way-of-kings?ac=1&from_search=true&qid=RRcOzq8Nd7&rank=1)
```{r}
# Function to get the recommended books
get_all_recs <- function(i){
    read_html(i) %>% 
    html_nodes(".cover a") %>% 
    html_attr("href") %>% 
    .[1:18] 
}
# Function to clean the formatted book
get_clean_recs <- function(x){
  x <- str_remove_all(x,"https://www.goodreads.com/book/show/\\d+.")
  x <- str_replace_all(x,"-|_"," ")
  x <- str_to_title(x)
  print(x)
}
```
```{r message=FALSE, include=FALSE}
# URL of Book
url <- "https://www.goodreads.com/book/show/7235533-the-way-of-kings?ac=1&from_search=true&qid=RRcOzq8Nd7&rank=1"
# Get recommended books
rec_books <- get_all_recs(url)
# Clean links up
rec_books_cleaned <- get_clean_recs(rec_books)
# Get links from reccommended books
recs <- unlist(map(rec_books,get_all_recs))
# Clean those links up
recs_cleaned <- get_clean_recs(recs)
# Create vector of original 18 reccomendations repeating 18 times each
books_like <- NULL
for (i in 1:18){
  books_like <- rep(rec_books_cleaned,each=18)
}
# Create dataframe with original parent reccommendations and child reccommendations
Way_of_Kings <- tibble(books_like,
                   book_recs=recs_cleaned)
```

```{r}
# Create collapsibleTree diagram
collapsibleTree(Way_of_Kings,c("books_like","book_recs"))
```

[Dune](https://www.goodreads.com/book/show/44767458-dune?from_search=true&from_srp=true&qid=oeA0uhsKyA&rank=1)
```{r}
# Function to get the recommended books
get_all_recs <- function(i){
    read_html(i) %>% 
    html_nodes(".cover a") %>% 
    html_attr("href") %>% 
    .[1:18] 
}
# Function to clean the formatted book
get_clean_recs <- function(x){
  x <- str_remove_all(x,"https://www.goodreads.com/book/show/\\d+.")
  x <- str_replace_all(x,"-|_"," ")
  x <- str_to_title(x)
  print(x)
}
```


```{r include=FALSE}
# URL of Book
url <- "https://www.goodreads.com/book/show/44767458-dune?from_search=true&from_srp=true&qid=oeA0uhsKyA&rank=1"
# Get recommended books
rec_books <- get_all_recs(url)
# Clean links up
rec_books_cleaned <- get_clean_recs(rec_books)
# Get links from reccommended books
recs <- unlist(map(rec_books,get_all_recs))
# Clean those links up
recs_cleaned <- get_clean_recs(recs)
# Create vector of original 18 reccomendations repeating 18 times each
books_like <- NULL
for (i in 1:18){
  books_like <- rep(rec_books_cleaned,each=18)
}
# Create dataframe with original parent reccommendations and child reccommendations
Dune <- tibble(books_like,
                   book_recs=recs_cleaned)
```

```{r}
# Create collapsibleTree diagram
collapsibleTree(Dune,c("books_like","book_recs"))
```

[Illuminae](https://www.goodreads.com/book/show/23395680-illuminae?ac=1&from_search=true&qid=Snhznx0D1y&rank=2)
```{r}
# Function to get the recommended books
get_all_recs <- function(i){
    read_html(i) %>% 
    html_nodes(".cover a") %>% 
    html_attr("href") %>% 
    .[1:18] 
}
# Function to clean the formatted book
get_clean_recs <- function(x){
  x <- str_remove_all(x,"https://www.goodreads.com/book/show/\\d+.")
  x <- str_replace_all(x,"-|_"," ")
  x <- str_to_title(x)
  print(x)
}
```

```{r include=FALSE}
# URL of Book
url <- "https://www.goodreads.com/book/show/23395680-illuminae?ac=1&from_search=true&qid=Snhznx0D1y&rank=2"
# Get recommended books
rec_books <- get_all_recs(url)
# Clean links up
rec_books_cleaned <- get_clean_recs(rec_books)
# Get links from reccommended books
recs <- unlist(map(rec_books,get_all_recs))
# Clean those links up
recs_cleaned <- get_clean_recs(recs)
# Create vector of original 18 reccomendations repeating 18 times each
books_like <- NULL
for (i in 1:18){
  books_like <- rep(rec_books_cleaned,each=18)
}
# Create dataframe with original parent reccommendations and child reccommendations
Dune <- tibble(books_like,
                   book_recs=recs_cleaned)
```

```{r}
# Create collapsibleTree diagram
collapsibleTree(Dune,c("books_like","book_recs"))
```
